highlighter: pygments
markdown: rdiscount
#pygments: true  
exclude: ['Rakefile', 'README.textile', 'config.rb', 'CNAME']
permalink: date
google_analytics_id: UA-50755011-1
timezone: America/Los_Angeles
sass:
    sass_dir: _scss
    style: :extended
host:        0.0.0.0
port:        4000
baseurl:     ""
url:         http://localhost:4000
destination: ./public_html